package FRONTERA;
import DAOS.DaoClientes;
import CONTROLADOR.ControlClientes;
import ENTIDAD.Clientes;
import java.math.BigInteger;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.print.*;

public class Factura extends javax.swing.JFrame implements Printable {

    public Factura() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Factura Generada");
        Toolkit t= Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/FRONTERA/favicon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        factura = new javax.swing.JPanel();
        txtNombreParqueaderoFactura = new javax.swing.JTextField();
        txtNITParqueaderoFactura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDireccionFactura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefonoFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPolizaFactura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoOperario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtMatriculafactura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEntradafactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSalidaFactura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDuracionFactura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBaseImponibleFactura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIvaFactura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorTotalFactura = new javax.swing.JTextField();
        puntosAcumulados = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRegimenFactura = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFormadePago = new javax.swing.JTextField();
        txtIdFactura = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        factura.setBackground(new java.awt.Color(255, 255, 255));
        factura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreParqueaderoFactura.setEditable(false);
        txtNombreParqueaderoFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreParqueaderoFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreParqueaderoFactura.setBorder(null);
        txtNombreParqueaderoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreParqueaderoFacturaActionPerformed(evt);
            }
        });
        factura.add(txtNombreParqueaderoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        txtNITParqueaderoFactura.setEditable(false);
        txtNITParqueaderoFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNITParqueaderoFactura.setBorder(null);
        factura.add(txtNITParqueaderoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, -1));

        jLabel1.setText("NIT:");
        factura.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, -1));

        txtDireccionFactura.setEditable(false);
        txtDireccionFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccionFactura.setBorder(null);
        txtDireccionFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionFacturaActionPerformed(evt);
            }
        });
        factura.add(txtDireccionFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, -1));

        jLabel2.setText("TEL:");
        factura.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, -1));

        txtTelefonoFactura.setEditable(false);
        txtTelefonoFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTelefonoFactura.setBorder(null);
        factura.add(txtTelefonoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 80, -1));

        jLabel3.setText("Poliza");
        factura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 40, -1));

        txtPolizaFactura.setEditable(false);
        txtPolizaFactura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPolizaFactura.setBorder(null);
        factura.add(txtPolizaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        jLabel4.setText("Código del Operario");
        factura.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, -1));

        txtCodigoOperario.setEditable(false);
        txtCodigoOperario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoOperario.setBorder(null);
        factura.add(txtCodigoOperario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, -1));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        factura.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 230, -1));

        jLabel5.setText("Matricula:");
        factura.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtMatriculafactura.setEditable(false);
        txtMatriculafactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMatriculafactura.setBorder(null);
        factura.add(txtMatriculafactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 80, -1));

        jLabel6.setText("Entrada:");
        factura.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtEntradafactura.setEditable(false);
        txtEntradafactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEntradafactura.setBorder(null);
        factura.add(txtEntradafactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, -1));

        jLabel7.setText("Salida:");
        factura.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtSalidaFactura.setEditable(false);
        txtSalidaFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalidaFactura.setBorder(null);
        factura.add(txtSalidaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, -1));

        jLabel8.setText("Duración (min):");
        factura.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtDuracionFactura.setEditable(false);
        txtDuracionFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDuracionFactura.setBorder(null);
        factura.add(txtDuracionFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, -1));

        jLabel9.setText("Base Imponible:");
        factura.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtBaseImponibleFactura.setEditable(false);
        txtBaseImponibleFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBaseImponibleFactura.setBorder(null);
        factura.add(txtBaseImponibleFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 140, -1));

        jLabel10.setText("IVA:");
        factura.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtIvaFactura.setEditable(false);
        txtIvaFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIvaFactura.setBorder(null);
        factura.add(txtIvaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 140, -1));

        jLabel11.setText("Valor TOTAL:");
        factura.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        txtValorTotalFactura.setEditable(false);
        txtValorTotalFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotalFactura.setBorder(null);
        txtValorTotalFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTotalFacturaActionPerformed(evt);
            }
        });
        factura.add(txtValorTotalFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 140, -1));

        puntosAcumulados.setText("Puntos Acumulados:");
        factura.add(puntosAcumulados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txtPuntosFactura.setEditable(false);
        txtPuntosFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPuntosFactura.setBorder(null);
        factura.add(txtPuntosFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 80, -1));

        jLabel12.setText("Regimen");
        factura.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, -1));

        txtRegimenFactura.setEditable(false);
        txtRegimenFactura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRegimenFactura.setBorder(null);
        txtRegimenFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegimenFacturaActionPerformed(evt);
            }
        });
        factura.add(txtRegimenFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, -1));

        jLabel13.setText("Forma de Pago");
        factura.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        txtFormadePago.setEditable(false);
        txtFormadePago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFormadePago.setBorder(null);
        txtFormadePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormadePagoActionPerformed(evt);
            }
        });
        factura.add(txtFormadePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 140, -1));

        txtIdFactura.setEditable(false);
        txtIdFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIdFactura.setBorder(null);
        txtIdFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFacturaActionPerformed(evt);
            }
        });
        factura.add(txtIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, -1));

        jLabel14.setText("FACTURA DE VENTA No.");
        factura.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        getContentPane().add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 420));

        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionFacturaActionPerformed

    private void txtNombreParqueaderoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreParqueaderoFacturaActionPerformed
        
    }//GEN-LAST:event_txtNombreParqueaderoFacturaActionPerformed

    private void txtValorTotalFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalFacturaActionPerformed

    private void txtRegimenFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegimenFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegimenFacturaActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            PrinterJob gap = PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top = gap.printDialog();
            if(top){
                gap.print();
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "ERROR DE PROGRAMA","Error\n"+ pex, JOptionPane.INFORMATION_MESSAGE);
        }
        
        dispose();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtFormadePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormadePagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormadePagoActionPerformed

    private void txtIdFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JPanel factura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel puntosAcumulados;
    public static javax.swing.JTextField txtBaseImponibleFactura;
    public static javax.swing.JTextField txtCodigoOperario;
    public static javax.swing.JTextField txtDireccionFactura;
    public static javax.swing.JTextField txtDuracionFactura;
    public static javax.swing.JTextField txtEntradafactura;
    public static javax.swing.JTextField txtFormadePago;
    public static javax.swing.JTextField txtIdFactura;
    public static javax.swing.JTextField txtIvaFactura;
    public static javax.swing.JTextField txtMatriculafactura;
    public static javax.swing.JTextField txtNITParqueaderoFactura;
    public static javax.swing.JTextField txtNombreParqueaderoFactura;
    public static javax.swing.JTextField txtPolizaFactura;
    public static final javax.swing.JTextField txtPuntosFactura = new javax.swing.JTextField();
    public static javax.swing.JTextField txtRegimenFactura;
    public static javax.swing.JTextField txtSalidaFactura;
    public static javax.swing.JTextField txtTelefonoFactura;
    public static javax.swing.JTextField txtValorTotalFactura;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if(index>0){
            return NO_SUCH_PAGE; //para hacer una sola impresión
        }
        
        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX()+30, pagfor.getImageableY()+30);
        hub.scale(1.0,1.0);
        factura.printAll(graf);
        return PAGE_EXISTS;
    }
}
