SELECT
     CLIENTES."MATRICULA" AS CLIENTES_MATRICULA,
     CLIENTES."TIPO_VEHICULO" AS CLIENTES_TIPO_VEHICULO,
     CLIENTES."ENTRADA" AS CLIENTES_ENTRADA
FROM
     "ADMINISTRADOR"."CLIENTES" CLIENTES
WHERE
     ENTRADA LIKE '$P!{fechaEntrada}%'