SELECT
     PARQUEADERO."NIT" AS PARQUEADERO_NIT,
     PARQUEADERO."DIRECCION" AS PARQUEADERO_DIRECCION,
     PARQUEADERO."POLIZA" AS PARQUEADERO_POLIZA,
     PARQUEADERO."RAZON_SOCIAL" AS PARQUEADERO_RAZON_SOCIAL,
     PARQUEADERO."REGIMEN" AS PARQUEADERO_REGIMEN,
     PARQUEADERO."TELEFONO" AS PARQUEADERO_TELEFONO
FROM
     "ADMINISTRADOR"."PARQUEADERO" PARQUEADERO